export const StyleMappings = {
  color: "color",
  opacity: "opacity",

  font: "font",
  fontFamily: "font-family",
  fontSize: addPx("font-size"),
  fontStyle: "font-style",
  fontVariant: "font-variant",
  fontWeight: "font-weight",
  fontStretch: "font-stretch",
  fontFeatureSettings: "font-feature-settings",
  "-gtk-dpi": "-gtk-dpi",

  caretColor: "caret-color",
  "-gtk-secondary-caret-color": "-gtk-secondary-caret-color",

  letterSpacing: addPx("letter-spacing"),
  textDecorationLine: "text-decoration-line",
  textDecorationColor: "text-decoration-color",
  textDecorationStyle: "text-decoration-style",
  textDecoration: "text-decoration",
  textShadow: "text-shadow",

  "-gtk-icon-source": "-gtk-icon-source",
  "-gtk-icon-transform": "-gtk-icon-transform",
  "-gtk-icon-style": "-gtk-icon-style",
  "-gtk-icon-theme": "-gtk-icon-theme",
  "-gtk-icon-palette": "-gtk-icon-palette",
  "-gtk-icon-shadow": "-gtk-icon-shadow",
  "-gtk-icon-effect": "-gtk-icon-effect",

  minWidth: addPx("min-width"),
  minHeight: addPx("min-height"),
  marginTop: addPx("margin-top"),
  marginRight: addPx("margin-right"),
  marginBottom: addPx("margin-bottom"),
  marginLeft: addPx("margin-left"),
  paddingTop: addPx("padding-top"),
  paddingRight: addPx("padding-right"),
  paddingBottom: addPx("padding-bottom"),
  paddingLeft: addPx("padding-left"),
  margin: addPx("margin"),
  padding: addPx("padding"),

  borderTopWidth: addPx("border-top-width"),
  borderRightWidth: addPx("border-right-width"),
  borderBottomWidth: addPx("border-bottom-width"),
  borderLeftWidth: addPx("border-left-width"),
  borderTopStyle: "border-top-style",
  borderRightStyle: "border-right-style",
  borderBottomStyle: "border-bottom-style",
  borderLeftStyle: "border-left-style",
  borderTopRightRadius: addPx("border-top-right-radius"),
  borderBottomRightRadius: addPx("border-bottom-right-radius"),
  borderBottomLeftRadius: addPx("border-bottom-left-radius"),
  borderTopLeftRadius: addPx("border-top-left-radius"),
  borderTopColor: "border-top-color",
  borderRightColor: "border-right-color",
  borderBottomColor: "border-bottom-color",
  borderLeftColor: "border-left-color",
  borderImageSource: "border-image-source",
  borderImageRepeat: "border-image-repeat",
  borderImageSlice: "border-image-slice",
  borderImageWidth: "border-image-width",
  borderWidth: addPx("border-width"),
  borderStyle: "border-style",
  borderColor: "border-color",
  borderTop: "border-top",
  borderRight: "border-right",
  borderBottom: "border-bottom",
  borderLeft: "border-left",
  border: "border",
  borderRadius: addPx("border-radius"),
  borderImage: "border-image",

  outlineStyle: "outline-style",
  outlineWidth: addPx("outline-width"),
  outlineColor: "outline-color",
  outlineOffset: addPx("outline-offset"),
  outline: "outline",
  "-gtk-outline-top-left-radius": addPx("-gtk-outline-top-left-radius"),
  "-gtk-outline-top-right-radius": addPx("-gtk-outline-top-right-radius"),
  "-gtk-outline-bottom-right-radius": addPx("-gtk-outline-bottom-right-radius"),
  "-gtk-outline-bottom-left-radius": addPx("-gtk-outline-bottom-left-radius"),
  "-gtk-outline-radius": addPx("-gtk-outline-radius"),

  backgroundColor: "background-color",
  backgroundClip: "background-clip",
  backgroundOrigin: "background-origin",
  backgroundSize: addPx("background-size"),
  backgroundPosition: addPx("background-position"),
  backgroundRepeat: "background-repeat",
  backgroundImage: "background-image",
  backgroundBlendMode: "background-blend-mode",
  boxShadow: "box-shadow",
  background: "background",

  "-gtk-key-bindings": "-gtk-key-bindings",

  flexDirection: "!",
  transition: "transition",
};

export function addPx(k: string) {
  return (v: any) => ({
    [k]: typeof v == "number" ? `${v}px` : v,
  });
}
